Try test-job again

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -884,15 +884,18 @@ package-oci:
 verify_maven_central_deployment:
   image: registry.ddbuild.io/images/base/gbi-ubuntu_2204:release
   stage: publish
-  needs: [ deploy_to_maven_central ]
+  # needs: [ deploy_to_maven_central ]
   rules:
     - if: '$POPULATE_CACHE'
       when: never
-    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
-      when: on_success
+    # - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
+    #   when: on_success
+    - when: manual
+      allow_failure: true
   script:
     - |
-      export VERSION=${CI_COMMIT_TAG##v}
+      export VERSION=1.51.2
+      # export VERSION=${CI_COMMIT_TAG##v}
       ARTIFACT_URLS=(
         "https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/${VERSION}/dd-java-agent-${VERSION}.jar"
         "https://repo1.maven.org/maven2/com/datadoghq/dd-trace-api/${VERSION}/dd-trace-api-${VERSION}.jar"
@@ -921,11 +924,36 @@ verify_maven_central_deployment:
         fi
         sleep $DELAY
       done
+      # TODO: remove this
+      echo "The job was successful, but what does test-job do if this job fails?"
+      exit 1
 
-publishing-gate:
+test-job:
+  stage: publish
   needs:
     - job: verify_maven_central_deployment
-      optional: true # Allow job to run even if the verify_maven_central_deployment job fails
+      optional: true
+  rules:
+    - if: '$POPULATE_CACHE'
+      when: never
+    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
+      when: on_success
+    - when: manual
+      allow_failure: true
+  script:
+    - echo "Hello, world!"
+
+# publishing-gate:
+#   needs:
+#     - job: verify_maven_central_deployment
+#       optional: true
+#   rules:
+#     - if: '$POPULATE_CACHE'
+#       when: never
+#     - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
+#       when: on_success
+#     - when: manual
+#       allow_failure: true
 
 configure_system_tests:
   variables:
