Graceful error handling in .gitlab/find-gh-base-ref.sh (#9074)
Co-authored-by: Brice Dutheil <brice.dutheil@gmail.com>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -123,7 +123,11 @@ default:
   - |
     if [[ ! $CI_COMMIT_BRANCH =~ ^(master|release/.*)$ ]]; then
       export GIT_BASE_REF=$(.gitlab/find-gh-base-ref.sh)
-      export GRADLE_PARAMS="$GRADLE_PARAMS -PgitBaseRef=origin/$GIT_BASE_REF"
+      if [[ -n "$GIT_BASE_REF" ]]; then
+        export GRADLE_PARAMS="$GRADLE_PARAMS -PgitBaseRef=origin/$GIT_BASE_REF"
+      else
+        echo "Failed to find base ref for PR" >&2
+      fi
     fi
 
 .gradle_build: &gradle_build
