config.yml only get test results for instr tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -560,12 +560,20 @@ jobs:
           name: Get APM Test Agent Trace Check Results
           when: always
           command: |
+            set +e  # Disable exiting from testagent response failure
+            STATUS_RESPONSE=$(curl -s -w "\n%{http_code}" http://localhost:8126/info) || true
+            set -e
+            STATUS_RESPONSE_CODE=$(echo "STATUS_RESPONSE" | awk 'END {print $NF}')
+            if [[ $STATUS_RESPONSE_CODE -eq 200 ]]; then
+              echo "APM Test Agent is running. (HTTP 200)"
+            else
+              echo "APM Test Agent is not running and was not used for testing. No checks failed."
+              exit 0
+            fi
             RESPONSE=$(curl -s -w "\n%{http_code}" -o response.txt http://localhost:8126/test/check_trace/failures)
             RESPONSE_CODE=$(echo "$RESPONSE" | awk 'END {print $NF}')
             if [[ $RESPONSE_CODE -eq 200 ]]; then
               echo "All APM Test Agent Check Traces returned successful! (HTTP 200)"
-            elif [[ $RESPONSE_CODE -eq 404 ]]; then
-              echo "APM Test Agent was not used for testing. No checks failed."
             else
               echo "APM Test Agent Check Traces failed with response code: $RESPONSE_CODE"
               echo "Failures:"
